pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/olegkoj/jupiter-cloud-automation-csharp.git'
        bat "dir"
      }
    }
    stage('Restore Dependencies') {
      steps {
        dir('JupiterCloudAutomation') {
          bat "dotnet restore JupiterCloudAutomation.csproj"
        }
      }
    }
    stage('Build') {
      steps {
        dir('JupiterCloudAutomation') {
          bat "dotnet build JupiterCloudAutomation.csproj --configuration Release"
        }
      }
    }
    stage('Install Playwright Browsers') {
      steps {
        dir('JupiterCloudAutomation') {
          bat "pwsh bin\\Release\\net8.0\\playwright.ps1 install"
        }
      }
    }
    stage('Run Tests') {
      steps {
        dir('JupiterCloudAutomation') {
          bat "dotnet test JupiterCloudAutomation.csproj --configuration Release --no-build --logger \"console;verbosity=detailed\""
        }
      }
    }
    stage('Generate Report') {
      steps {
        archiveArtifacts 'JupiterCloudAutomation/playwright-report/**'
      }
    }
  }
  post {
    always {
      publishHTML(target: [
        reportDir: 'JupiterCloudAutomation/playwright-report',
        reportFiles: 'index.html',
        reportName: 'Playwright Report'
      ])
    }
  }
}